all: create  clean

create:
	pdflatex  main-debs2022-presentation.tex
#	bibtex    main-debs2022-presentation
	pdflatex  main-debs2022-presentation.tex

clean:
	rm -rf *.aux  *.nav  *.vrb  *.log  *.out *.snm *.toc *.gz *.bbl *.blg *.fls *.fdb_latexmk
