// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: main/proto/challenger.proto

package de.tum.i13.challenge;

public interface CrossoverEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Challenger.CrossoverEvent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.google.protobuf.Timestamp ts = 1;</code>
   * @return Whether the ts field is set.
   */
  boolean hasTs();
  /**
   * <code>.google.protobuf.Timestamp ts = 1;</code>
   * @return The ts.
   */
  com.google.protobuf.Timestamp getTs();
  /**
   * <code>.google.protobuf.Timestamp ts = 1;</code>
   */
  com.google.protobuf.TimestampOrBuilder getTsOrBuilder();

  /**
   * <code>string symbol = 2;</code>
   * @return The symbol.
   */
  java.lang.String getSymbol();
  /**
   * <code>string symbol = 2;</code>
   * @return The bytes for symbol.
   */
  com.google.protobuf.ByteString
      getSymbolBytes();

  /**
   * <code>.Challenger.SecurityType security_type = 3;</code>
   * @return The enum numeric value on the wire for securityType.
   */
  int getSecurityTypeValue();
  /**
   * <code>.Challenger.SecurityType security_type = 3;</code>
   * @return The securityType.
   */
  de.tum.i13.challenge.SecurityType getSecurityType();

  /**
   * <code>.Challenger.CrossoverEvent.SignalType signal_type = 4;</code>
   * @return The enum numeric value on the wire for signalType.
   */
  int getSignalTypeValue();
  /**
   * <code>.Challenger.CrossoverEvent.SignalType signal_type = 4;</code>
   * @return The signalType.
   */
  de.tum.i13.challenge.CrossoverEvent.SignalType getSignalType();
}
