// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: main/proto/challenger.proto

package de.tum.i13.challenge;

public interface ResultQ2OrBuilder extends
    // @@protoc_insertion_point(interface_extends:Challenger.ResultQ2)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 benchmark_id = 1;</code>
   * @return The benchmarkId.
   */
  long getBenchmarkId();

  /**
   * <code>int64 batch_seq_id = 2;</code>
   * @return The batchSeqId.
   */
  long getBatchSeqId();

  /**
   * <code>repeated .Challenger.CrossoverEvent crossover_events = 3;</code>
   */
  java.util.List<de.tum.i13.challenge.CrossoverEvent> 
      getCrossoverEventsList();
  /**
   * <code>repeated .Challenger.CrossoverEvent crossover_events = 3;</code>
   */
  de.tum.i13.challenge.CrossoverEvent getCrossoverEvents(int index);
  /**
   * <code>repeated .Challenger.CrossoverEvent crossover_events = 3;</code>
   */
  int getCrossoverEventsCount();
  /**
   * <code>repeated .Challenger.CrossoverEvent crossover_events = 3;</code>
   */
  java.util.List<? extends de.tum.i13.challenge.CrossoverEventOrBuilder> 
      getCrossoverEventsOrBuilderList();
  /**
   * <code>repeated .Challenger.CrossoverEvent crossover_events = 3;</code>
   */
  de.tum.i13.challenge.CrossoverEventOrBuilder getCrossoverEventsOrBuilder(
      int index);
}
